create table if not exists public.communities (
  id bigint generated by default as identity primary key,
  key text not null unique,
  label text not null,
  active boolean not null default false,
  zipcodes text[] not null default '{}',
  address_items jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint communities_key_format check (key ~ '^[a-z0-9_-]+$'),
  constraint communities_address_items_array check (jsonb_typeof(address_items) = 'array')
);

create index if not exists communities_active_idx on public.communities (active);
create index if not exists communities_label_idx on public.communities (label);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_communities_updated_at on public.communities;
create trigger trg_communities_updated_at
before update on public.communities
for each row
execute function public.set_updated_at();

alter table public.communities enable row level security;

create or replace function public.is_admin_user()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.users u
    where u.id = auth.uid()
      and lower(u.role) = 'admin'
  );
$$;

grant execute on function public.is_admin_user() to authenticated;

create policy "communities_select_all_authenticated"
on public.communities
for select
to authenticated
using (true);

create policy "communities_insert_admin_only"
on public.communities
for insert
to authenticated
with check (public.is_admin_user());

create policy "communities_update_admin_only"
on public.communities
for update
to authenticated
using (public.is_admin_user())
with check (public.is_admin_user());

create policy "communities_delete_admin_only"
on public.communities
for delete
to authenticated
using (public.is_admin_user());

insert into public.communities (key, label, active)
values
  ('andarai', 'Andaraí', false),
  ('arara', 'Arara', false),
  ('barreira', 'Barreira do Vasco', false),
  ('cdd', 'Cidade de Deus', false),
  ('ceuazul', 'Céu Azul', false),
  ('cpx', 'Complexo do Alemão', false),
  ('formiga', 'Morro da Formiga', false),
  ('jacare', 'Jacarezinho', false),
  ('lins', 'Lins', false),
  ('macaco', 'Morro do Macaco', false),
  ('mandela2', 'Mandela 2', true),
  ('mangueira', 'Mangueira', false),
  ('manguinhos', 'Manguinhos', false),
  ('ppg', 'PPG', false),
  ('pdm', 'Parque das Missões', false),
  ('rocinha', 'Rocinha', false),
  ('saojoao', 'São João', false),
  ('sc', 'São Carlos', false),
  ('tuiuti', 'Tuiuti', false),
  ('urubu', 'Urubu', false),
  ('viladojoao', 'Vila do João', false),
  ('pinheiro', 'Pinheiro', false),
  ('timbau', 'Morro do Timbau', false),
  ('salsa', 'Salsa e Merengue', false),
  ('esperanca', 'Conjunto Esperança', false),
  ('baixa', 'Baixa do Sapateiro', false),
  ('uniao', 'Parque União', false),
  ('holanda', 'Nova Holanda', false),
  ('boca', 'Boca do Mato', false),
  ('barao', 'Barão', false),
  ('vidigal', 'Vidigal', false),
  ('uruguaiana', 'Uruguaiana', false)
on conflict (key) do update set
  label = excluded.label,
  active = excluded.active;

update public.communities
set
  zipcodes = array['20911-300'],
  address_items = '[
    {"value":"q-1","label":"Quadra 1","type":"block"},
    {"value":"q-2","label":"Quadra 2","type":"block"},
    {"value":"q-3","label":"Quadra 3","type":"block"},
    {"value":"q-4","label":"Quadra 4","type":"block"},
    {"value":"q-5","label":"Quadra 5","type":"block"},
    {"value":"q-6","label":"Quadra 6","type":"block"},
    {"value":"q-7","label":"Quadra 7","type":"block"},
    {"value":"q-8","label":"Quadra 8","type":"block"},
    {"value":"q-9","label":"Quadra 9","type":"block"},
    {"value":"q-10","label":"Quadra 10","type":"block"},
    {"value":"q-11","label":"Quadra 11","type":"block"},
    {"value":"q-12","label":"Quadra 12","type":"block"},
    {"value":"q-13","label":"Quadra 13","type":"block"},
    {"value":"q-14","label":"Quadra 14","type":"block"},
    {"value":"q-15","label":"Quadra 15","type":"block"},
    {"value":"q-16","label":"Quadra 16","type":"block"},
    {"value":"q-17","label":"Quadra 17","type":"block"},
    {"value":"q-18","label":"Quadra 18","type":"block"},
    {"value":"q-19","label":"Quadra 19","type":"block"},
    {"value":"q-20","label":"Quadra 20","type":"block"},
    {"value":"q-21","label":"Quadra 21","type":"block"},
    {"value":"q-22","label":"Quadra 22","type":"block"},
    {"value":"q-23","label":"Quadra 23","type":"block"},
    {"value":"q-24","label":"Quadra 24","type":"block"},
    {"value":"q-25","label":"Quadra 25","type":"block"},
    {"value":"q-26","label":"Quadra 26","type":"block"},
    {"value":"q-27","label":"Quadra 27","type":"block"},
    {"value":"q-28","label":"Quadra 28","type":"block"},
    {"value":"q-29","label":"Quadra 29","type":"block"},
    {"value":"q-30","label":"Quadra 30","type":"block"},
    {"value":"q-31","label":"Quadra 31","type":"block"},
    {"value":"q-32","label":"Quadra 32","type":"block"},
    {"value":"q-33","label":"Quadra 33","type":"block"},
    {"value":"q-34","label":"Quadra 34","type":"block"},
    {"value":"q-35","label":"Quadra 35","type":"block"},
    {"value":"q-36","label":"Quadra 36","type":"block"},
    {"value":"q-37","label":"Quadra 37","type":"block"},
    {"value":"q-38","label":"Quadra 38","type":"block"},
    {"value":"q-39","label":"Quadra 39","type":"block"},
    {"value":"q-40","label":"Quadra 40","type":"block"},
    {"value":"tv-1","label":"Terreninho - Vila 1","type":"village"},
    {"value":"tv-2","label":"Terreninho - Vila 2","type":"village"},
    {"value":"tv-3","label":"Terreninho - Vila 3","type":"village"},
    {"value":"tv-4","label":"Terreninho - Vila 4","type":"village"},
    {"value":"tv-5","label":"Terreninho - Vila 5","type":"village"},
    {"value":"tr-1","label":"Terreninho - Rua 1","type":"street"},
    {"value":"tr-2","label":"Terreninho - Rua 2","type":"street"},
    {"value":"tr-3","label":"Terreninho - Rua 3","type":"street"},
    {"value":"tr-4","label":"Terreninho - Rua 4","type":"street"},
    {"value":"tr-5","label":"Terreninho - Rua 5","type":"street"},
    {"value":"tr-6","label":"Terreninho - Rua 6","type":"street"},
    {"value":"tr-7","label":"Terreninho - Rua 7","type":"street"},
    {"value":"tr-8","label":"Terreninho - Rua 8","type":"street"},
    {"value":"tr-9","label":"Terreninho - Rua 9","type":"street"},
    {"value":"tl-1","label":"Terreninho - Travessa 1","type":"lane"},
    {"value":"tl-2","label":"Terreninho - Travessa 2","type":"lane"},
    {"value":"tl-3","label":"Terreninho - Travessa 3","type":"lane"},
    {"value":"tl-4","label":"Terreninho - Travessa 4","type":"lane"},
    {"value":"tl-5","label":"Terreninho - Travessa 5","type":"lane"},
    {"value":"tl-6","label":"Terreninho - Travessa 6","type":"lane"},
    {"value":"tl-7","label":"Terreninho - Travessa 7","type":"lane"},
    {"value":"tl-8","label":"Terreninho - Travessa 8","type":"lane"}
  ]'::jsonb
where key = 'mandela2';
